export const ADD_TODO="ADD_TODO"
export const REMOVE_TODO="REMOVE_TODO"



export const ADD_TODO_LODING="ADD_TODO_LODING"
export const ADD_TODO_SUCCESS="ADD_TODO_LODING"
export const ADD_TODO_ERROR="ADD_TODO_LODING"
